services:
  api:
    build:
      context: .
      args:
        - ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
