name: Api Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Tests Environment Variables
        run: cp .env.example .env
      - name: Test
        run: docker-compose run --rm api sh -c "python /wait_for_service.py postgres 5432 && python manage.py test"
      - name: Lint
        run: docker-compose run --rm api sh -c "flake8"
